### ISSUE TITLE
InlayHints work only with only_current_line = false

### ISSUE THREAD

**Issue by crisidev** [simrat39/rust-tools.nvim#163]
The inlay hints are working for me only when

```
only_current_line = false
```

If this option is set to true, they do no show up when I am on a line where the inlay hint should be there.

This was working fine until recently, but I am not sure when it stopped working for me.

I am not sure how to debug this to ensure it is not something else clashing with rust-tools!

Any help would be much appreciated.

**Comment by simrat39** [comment]
Looks like rust-analyzer recently changed the spec which might have broken only_current_line, will have a look. Thanks for the report!

**Comment by P1n3appl3** [comment]
I'm seeing this behavior too, worth noting that the `:RustToggleInlayHints` (as well as `Set` and `Disable`) have also stopped working, probably due to the same spec change.

**Comment by simrat39** [comment]
OK, so I am rewriting the inlay hints code (and a bit more of the plugin), I would really appreciate if you could test the https://github.com/simrat39/rust-tools.nvim/tree/modularize_and_inlay_rewrite branch and see if it fixes your issue

**Comment by crisidev** [comment]
I have just tested it and works perfectly with my setup.

**Comment by dathinaios** [comment]
I have similar issues with inlay hints. Should I switch to the branch @simrat39? I see it is missing a couple of commits and the last commits on main where related to the `LSP` functionality so I am not sure if I should 🤔

**Comment by simrat39** [comment]
> 

Thanks for testing! I'll be merging it soon once we get some more testers

**Comment by fdelacruz** [comment]
I just would like to report that the InlayHints are working beautifully in this [modularize_and_inlay_rewrite](https://github.com/simrat39/rust-tools.nvim/tree/modularize_and_inlay_rewrite ) branch with my setup. Contrary to the OP, the `only_current_line` option is working as intended. On the other hand, `show_variable_name` is not.

**Comment by Zwo1in** [comment]
InlayHints indeed are working on this branch, however I've encountered an error when using `RustHoverActions`:

```
Error executing vim.schedule lua callback: vim/shared.lua:0: after the second argument: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'tbl_extend'
        ...r/start/rust-tools.nvim/lua/rust-tools/hover_actions.lua:90: in function 'fn'
        ...ker/start/rust-tools.nvim/lua/rust-tools/utils/utils.lua:101: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1025: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by dathinaios** [comment]
Can confirm that I have the same issue as @Zwo1in

**Comment by fdelacruz** [comment]
Me too!!
It doesn't happen in master.

**Comment by simrat39** [comment]
@Zwo1in @dathinaios @fdelacruz Should be fixed now!

**Comment by dathinaios** [comment]
Thanks! I did a quick test and it indeed seems to be working fine now 🙂

**Comment by sgoudham** [comment]
Hi, I sadly still have the same issue on the latest versions of rust-tools and rust-analyzer (2022-05-17 stable)

Is there something wrong with my config? 
```rust
autoSetHints = true,
hover_with_actions = true,
runnables = {
    use_telescope = true
},
inlay_hints = {
    show_parameter_hints = false,
    other_hints_prefix = "<< ",
    only_current_line = true,
    only_current_line_autocmd = "CursorMoved,CursorMovedI"
}
```

**Comment by dathinaios** [comment]
> Hi, I sadly still have the same issue on the latest versions of rust-tools and rust-analyzer (2022-05-17 stable)

Are you on the [modularize_and_inlay_rewrite](https://github.com/simrat39/rust-tools.nvim/tree/modularize_and_inlay_rewrite) cause I don't think this has been merged to master yet.

**Comment by Zwo1in** [comment]
Hi, any progress on merging this?

**Comment by supetronix** [comment]
Hi,

I tried below in LunarVim "config.lua" but inlay hints still didn't work for me (I tried with or without "config" block but same results):


`  {
    "simrat39/rust-tools.nvim",
    branch = "modularize_and_inlay_rewrite",
    config = function()
      local lsp_installer_servers = require "nvim-lsp-installer.servers"
      local _, requested_server = lsp_installer_servers.get_server "rust_analyzer"
      require("rust-tools").setup({
        tools = {
          autoSetHints = true,
          hover_with_actions = true,
          inlay_hints = {

            -- Only show inlay hints for the current line
            only_current_line = false,

            -- Event which triggers a refersh of the inlay hints.
            -- You can make this "CursorMoved" or "CursorMoved,CursorMovedI" but
            -- not that this may cause higher CPU usage.
            -- This option is only respected when only_current_line and
            -- autoSetHints both are true.
            only_current_line_autocmd = "CursorHold",

            -- whether to show parameter hints with the inlay hints or not
            -- default: true
            show_parameter_hints = true,

            -- whether to show variable name before type hints with the inlay hints or not
            -- default: false
            show_variable_name = false,

            -- prefix for parameter hints
            -- default: "<-"
            parameter_hints_prefix = "<- ",

            -- prefix for all the other hints (type, chaining)
            -- default: "=>"
            other_hints_prefix = "=> ",

            -- whether to align to the lenght of the longest line in the file
            max_len_align = false,

            -- padding from the left if max_len_align is true
            max_len_align_padding = 1,

            -- whether to align to the extreme right or not
            right_align = false,

            -- padding from the right if right_align is true
            right_align_padding = 7,

            -- The color of the hints
            highlight = "Comment",
          },
          runnables = {
            use_telescope = true,
          },
        },
        server = {
          cmd_env = requested_server._default_options.cmd_env,
          on_attach = require("lvim.lsp").common_on_attach,
          on_init = require("lvim.lsp").common_on_init,
        },
      })
    end,
    ft = { "rust", "rs" },
  },
`

any pointers?

Thanks
